networks:
  nginx-network:
    external: false

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    networks:
      - nginx-network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx_acme
    environment:
      - DEFAULT_EMAIL=juanjosebogado93@gmail.com # ⚠️ CAMBIALO por uno tuyo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    restart: always
    networks:
      - nginx-network

  hacienda:
    build: ./Hacienda-0.0/hacienda_0
    container_name: hacienda_app
    expose:
      - "8001"
    environment:
      - VIRTUAL_HOST=www.juanbogado.dev
      - VIRTUAL_PATH=/hacienda/
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=www.juanbogado.dev
      - LETSENCRYPT_EMAIL=juanjosebogado93@gmail.com
    networks:
      - nginx-network
    restart: always

  cattle:
    build: ./cattlelog
    container_name: cattle_app
    expose:
      - "8002"
    environment:
      - VIRTUAL_HOST=www.juanbogado.dev
      - VIRTUAL_PATH=/cattlelog/
      - VIRTUAL_PORT=8002
      - LETSENCRYPT_HOST=www.juanbogado.dev
      - LETSENCRYPT_EMAIL=juanjosebogado93@gmail.com
    networks:
      - nginx-network
    restart: always

  landing:
    build: ./portfolio
    container_name: landingpage
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=www.juanbogado.dev
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.juanbogado.dev
      - LETSENCRYPT_EMAIL=tu-email@gmail.com
    networks:
      - nginx-network
    restart: always
