# services:
#   web:
#     build: .
#     container_name: hacienda_app
#     ports:
#       - "8001:8001"
#     environment:
#       - DJANGO_SETTINGS_MODULE=hacienda_0.settings
#     volumes:
#       - .:/app

services:
  cattle:
    build:
      context: ./cattlelog
    container_name: cattle_app
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=cattlelog.settings
    volumes:
      - ./cattlelog:/app

  landing:
    build:
      context: ./portfolio
    container_name: landingpage
    ports:
      - "80:80"
    volumes:
      - ./portfolio:/usr/share/nginx/html
